### ISSUE TITLE
Make it a package

### ISSUE THREAD

**Issue by bdlukaa** [f2acode/pricing_cards#1]
You actually created a plugin instead of a plugin. Packages can be used at any platform, but plugins can only be used on the platforms specified in pubspec.yaml.

Here, it should show web, windows, macos and linux as supported platforms, but it's only showing Android and iOS
![2021-05-02 (2)](https://user-images.githubusercontent.com/45696119/116815857-e21b7a00-ab35-11eb-87c7-6248d2120a53.png)

**Comment by f2acode** [comment]
Thanks! I just fixed it, now it's possible to use in any platform.

![Screenshot from 2021-05-04 12-15-12](https://user-images.githubusercontent.com/12521100/117026775-702c6780-acd2-11eb-9458-7bfe8b43391a.png)

**Comment by bdlukaa** [comment]
Nice. The android and iOS folder can be deleted
